-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Opiekunowie"
(
    "IdOpiekuna" integer NOT NULL,
    "IdZwierzecia" integer NOT NULL,
    "Imie" character varying(50)[] COLLATE pg_catalog."default" NOT NULL,
    "Nazwisko" character varying(50)[] COLLATE pg_catalog."default" NOT NULL,
    "IloscPodOpieka" integer NOT NULL,
    "Doswiadczenie" integer NOT NULL,
    "NrTel" character varying(9)[] COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Opiekunowie_pkey" PRIMARY KEY ("IdOpiekuna")
);

CREATE TABLE IF NOT EXISTS public."Zdrowie"
(
    "IdZwierzecia" integer NOT NULL,
    "CzySczepiony" boolean NOT NULL,
    "Choroby" character varying(50)[] COLLATE pg_catalog."default",
    "Leki" character varying(50)[] COLLATE pg_catalog."default",
    CONSTRAINT "Zdrowie_pkey" PRIMARY KEY ("IdZwierzecia")
);

CREATE TABLE IF NOT EXISTS public."Zwierze"
(
    "IdZwierzecia" integer NOT NULL,
    "Imie" character varying(50)[] COLLATE pg_catalog."default" NOT NULL,
    "Gatunek" character varying(1) COLLATE pg_catalog."default" NOT NULL,
    "Plec" character varying(1) COLLATE pg_catalog."default" NOT NULL,
    "Rasa" character varying(50)[] COLLATE pg_catalog."default" NOT NULL,
    "Umaszczenie" character varying(50)[] COLLATE pg_catalog."default" NOT NULL,
    "Wielkosc" character varying(50)[] COLLATE pg_catalog."default" NOT NULL,
    "CzyDoAdopcji" boolean,
    "CzyPsy" boolean,
    "CzyKoty" boolean,
    "CzyDzieci" boolean,
    "NrKojca" integer,
    CONSTRAINT "Zwierze_pkey" PRIMARY KEY ("IdZwierzecia")
);

ALTER TABLE IF EXISTS public."Opiekunowie"
    ADD CONSTRAINT "Opiekunowie_IdZwierzecia_fkey" FOREIGN KEY ("IdZwierzecia")
    REFERENCES public."Zwierze" ("IdZwierzecia") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Zdrowie"
    ADD CONSTRAINT "idZwierzecia" FOREIGN KEY ("IdZwierzecia")
    REFERENCES public."Zwierze" ("IdZwierzecia") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "Zdrowie_pkey"
    ON public."Zdrowie"("IdZwierzecia");


ALTER TABLE IF EXISTS public."Zwierze"
    ADD CONSTRAINT "IdZwierzecia" FOREIGN KEY ("IdZwierzecia")
    REFERENCES public."Zdrowie" ("IdZwierzecia") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "Zwierze_pkey"
    ON public."Zwierze"("IdZwierzecia");

END;